# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-11-27 09:38
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incidents', '0010_auto_20170122_1208'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('django.forms.CharField', 'Char'), ('django.forms.BooleanField', 'Bool')], max_length=100)),
                ('widget_type', models.CharField(choices=[('django.forms.Textarea', 'Text Area'), ('django.forms.CheckboxInput', 'Check Box')], max_length=100, null=True)),
                ('label', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_answered', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.CharField(blank=True, max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.Question')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuestionGroup')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.Quiz')),
            ],
        ),
        migrations.CreateModel(
            name='QuizGroupQuestionOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.Question')),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuestionGroup')),
            ],
            options={
                'ordering': ['-order_index'],
            },
        ),
        migrations.CreateModel(
            name='QuizTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this specific quiz template', max_length=100)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidents.IncidentCategory')),
            ],
        ),
        migrations.CreateModel(
            name='QuizTemplateQuestionGroupOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('question_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuestionGroup')),
                ('quiz_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuizTemplate')),
            ],
            options={
                'ordering': ['-order_index'],
            },
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='question_groups',
            field=models.ManyToManyField(through='fir_userinteraction.QuizTemplateQuestionGroupOrder', to='fir_userinteraction.QuestionGroup', verbose_name='list of quiz groups'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='answers',
            field=models.ManyToManyField(through='fir_userinteraction.QuizAnswer', to='fir_userinteraction.Question'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='incident',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='incidents.Incident'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuizTemplate'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='questions',
            field=models.ManyToManyField(through='fir_userinteraction.QuizGroupQuestionOrder', to='fir_userinteraction.Question', verbose_name='list of questions in this group'),
        ),
    ]
