# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-31 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir_userinteraction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizWatchListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Email address for the watchlist', max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.Quiz')),
            ],
        ),
    ]
