# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 11:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir_userinteraction', '0002_quizwatchlistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizTemplateUsefulLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='Label for identifying the help list item', max_length=100)),
                ('text', models.TextField()),
                ('quiz_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuizTemplate')),
            ],
        ),
    ]
