# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 14:27
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fir_userinteraction', '0003_quiztemplateusefullink'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsefulLinkOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('quiz_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuizTemplate')),
            ],
            options={
                'ordering': ['-order_index'],
            },
        ),
        migrations.RemoveField(
            model_name='quiztemplateusefullink',
            name='quiz_template',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='PLEASE CHANGE', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.TextField(),
        ),
        migrations.AddField(
            model_name='usefullinkordering',
            name='template_useful_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fir_userinteraction.QuizTemplateUsefulLink'),
        ),
        migrations.AddField(
            model_name='quiztemplate',
            name='useful_links',
            field=models.ManyToManyField(through='fir_userinteraction.UsefulLinkOrdering', to='fir_userinteraction.QuizTemplateUsefulLink', verbose_name='list of useful links for template'),
        ),
    ]
