# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_userinteraction', '0004_auto_20180208_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztemplate',
            name='description',
            field=models.TextField(default='ADD DESCRIPTION'),
            preserve_default=False,
        ),
    ]
