# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-18 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fir_userinteraction', '0008_auto_20180509_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizanswer',
            name='answer_value',
            field=models.TextField(blank=True),
        ),
    ]
