stages:
  - deploy

redeploy_in_openshift:
  stage: deploy
  image: gitlab-registry.cern.ch/paas-tools/openshift-client
  script: "oc start-build fir --namespace cert-self-service --server https://openshift.cern.ch --token $CERT_SELF_SERVICE_DEPLOY_TOKEN"
